---
version: "3"
services:
  resultserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: docker/env_file
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - AUDIT_WRITE
  revproxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 443:443
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - AUDIT_WRITE
      - CHOWN
      - SETGID
      - SETUID

