---
version: "3"
services:
  resultserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: docker/env_file
  revproxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 443:443
